# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "мастер" ]
  pull_request:
    branches: [ "мастер" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Check types with mypy
      run: poetry run mypy --strict .
    - name: Lint with pylint
      run: poetry run pylint --recursive=y -j 0 .
    - name: Lint with pyright
      run: poetry run pyright
    - name: Lint with ruff
      run: poetry run ruff .
    - name: Check formatting with black
      run: poetry run black -l 79 --check .
    - name: Test with pytest
      run: poetry run pytest -vv -n auto --disable-socket
